CREATE TABLE user_kyc (
    autonid UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id VARCHAR(50),
    cif_id VARCHAR(50),
    stage INTEGER NOT NULL,
    cif_nid INTEGER NOT NULL,
    change_nid INTEGER NOT NULL,
    pending_cif_nid INTEGER NOT NULL,
    is_revised BOOLEAN NOT NULL,
    is_rejected BOOLEAN NOT NULL,
    is_finished BOOLEAN NOT NULL,
    note TEXT,
    branch VARCHAR(100),
    referal_number VARCHAR(50),
    account_status BOOLEAN,
    mobile_phone VARCHAR(50),
    email VARCHAR(200),
    fullname VARCHAR(200),
    spouse_relationship VARCHAR(50),
    spouse_name VARCHAR(200),
    mother_name VARCHAR(200),
    nationality INTEGER,
    idcard_country INTEGER,
    idcard_number VARCHAR(200),
    idcard_expire_date TIMESTAMP,
    sex INTEGER,
    birth_place VARCHAR(200),
    birth_date TIMESTAMP,
    religion INTEGER,
    marital_status INTEGER,
    education INTEGER,
    idcard_city INTEGER,
    idcard_district VARCHAR(200),
    idcard_subdistrict VARCHAR(200),
    idcard_rt VARCHAR(5),
    idcard_rw VARCHAR(5),
    idcard_zipcode VARCHAR(5),
    idcard_address VARCHAR(200),
    copy_id BOOLEAN,
    domicile_city INTEGER,
    domicile_district VARCHAR(200),
    domicile_subdistrict VARCHAR(200),
    domicile_rt VARCHAR(5),
    domicile_rw VARCHAR(5),
    domicile_zipcode VARCHAR(5),
    domicile_address VARCHAR(200),
    save_time TIMESTAMP NOT NULL,
    last_update TIMESTAMP NOT NULL,
    import_date TIMESTAMP,
    save_ip_address VARCHAR(100) NOT NULL,
    question_rdn INTEGER,
    bank_code INTEGER,
    bank_name VARCHAR(100),
    bank_branch VARCHAR(100),
    bank_account_holder VARCHAR(100),
    bank_account_number VARCHAR(100),
    question_npwp INTEGER,
    npwp_number VARCHAR(50),
    npwp_reason VARCHAR(100),
    company_name VARCHAR(100),
    company_address VARCHAR(200),
    fund_source VARCHAR(200),
    occupation INTEGER,
    occupation_text VARCHAR(200),
    nature_of_business INTEGER,
    nature_of_business_text VARCHAR(200),
    position INTEGER,
    position_text VARCHAR(200),
    income_per_annum INTEGER,
    fund_source_text VARCHAR(200),
    question1 VARCHAR(50),
    question1_text TEXT,
    question2 VARCHAR(50),
    question2_text TEXT,
    question3 VARCHAR(50),
    question3_text TEXT,
    question4 VARCHAR(50),
    question4_text TEXT,
    question5 VARCHAR(50),
    question5_text TEXT,
    question6 VARCHAR(50),
    question6_text TEXT,
    investment_objectives INTEGER,
    risk INTEGER,
    question_fatca VARCHAR(50),
    fatca1 VARCHAR(50),
    fatca2 VARCHAR(50),
    fatca3 VARCHAR(50),
    spouse_income_per_annum INTEGER,
    spouse_occupation INTEGER,
    spouse_occupation_text VARCHAR(200),
    spouse_position VARCHAR(200),
    spouse_nature_of_business VARCHAR(200),
    spouse_company_name VARCHAR(200),
    spouse_company_city INTEGER,
    spouse_company_zipcode VARCHAR(6),
    spouse_company_address VARCHAR(100),
    spouse_fund_source VARCHAR(200),
    spouse_fund_source_text VARCHAR(200),
    idcard_file VARCHAR(200),
    selfie_file VARCHAR(200),
    signature_file VARCHAR(200),
    sales INTEGER,
    spouse_relationship_text VARCHAR(50),
    education_text VARCHAR(200),
    is_imported BOOLEAN,
    company_city INTEGER,
    company_zipcode VARCHAR(6),
    birth_country VARCHAR(200),
    npwp_file VARCHAR(200)
);
