CREATE TABLE users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    handphone VARCHAR(100) NOT NULL,
    register_date TIMESTAMP NOT NULL,
    web_cif_id INTEGER NOT NULL,
    disable_login BOOLEAN NOT NULL,
    activate_code VARCHAR(100),
    activate_time TIMESTAMP,
    last_login TIMESTAMP,
    client_category INTEGER,
    last_resend_otp TIMESTAMP,
    otp_generated_link VARCHAR(100),
    reset_password_key VARCHAR(100),
    reset_password_flag INTEGER,
    reset_password_date TIMESTAMP,
    otp_generated_link_date TIMESTAMP,
    count_resend_activation INTEGER NOT NULL DEFAULT 0,
    picture TEXT,
    google_id TEXT
);
