name: Call Shuttle

on:
  schedule:
    - cron: "0 18 * * *" # 01:00 WIB
  workflow_dispatch:

jobs:
  refresh-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Call Shuttle
        run: |
          curl -s -f -X GET https://snakesystem-api.shuttle.app
